# Generated by Django 4.0.3 on 2022-05-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_rename_imagemodel_geeksmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.ImageField(blank=True, upload_to='reddit_images'),
        ),
    ]
