# Generated by Django 4.0.3 on 2022-05-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_alter_geeksmodel_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geeks_field',
            field=models.ImageField(blank=True, upload_to='geeksmodel_geeks_field'),
        ),
    ]
