# Generated by Django 4.0.3 on 2022-05-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_post_geeks_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='geeks_field',
            field=models.ImageField(blank=True, upload_to='media/reddit_images'),
        ),
    ]
