# Generated by Django 4.0.3 on 2022-05-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_delete_geeksmodel_alter_post_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='geeks_field',
            field=models.ImageField(blank=True, upload_to='reddit_images/'),
        ),
    ]
