# Generated by Django 4.0.3 on 2022-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0008_post_name_alter_post_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='geeks_field',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
